namespace DairyFlow.Web.Services;

/// <summary>
/// Simple key-based localizer. Reads AppState.Lang ("en" or "am") on every access
/// so components automatically render the current language when re-rendered.
/// </summary>
public class Localizer
{
    private readonly AppState _state;

    public Localizer(AppState state) => _state = state;

    public string this[string key]
    {
        get
        {
            if (_state.Lang == "am" && Am.TryGetValue(key, out var am)) return am;
            return En.TryGetValue(key, out var en) ? en : key;
        }
    }

    // ── English ──────────────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> En = new()
    {
        // App
        ["app.name"]        = "DairyFlow",
        ["app.tagline"]     = "Dairy Farm Management",

        // Nav
        ["nav.dashboard"]   = "Dashboard",
        ["nav.cows"]        = "Livestock",
        ["nav.milk"]        = "Milk Log",
        ["nav.sales"]       = "Sales",
        ["nav.health"]      = "Health",
        ["nav.expenses"]    = "Expenses",
        ["nav.feed"]        = "Feed Inventory",
        ["nav.feedtemplates"] = "Feeding Templates",
        ["nav.accounts"]    = "Accounts",

        // Feeding templates
        ["tmpl.title"]       = "Feeding Templates",
        ["tmpl.add"]         = "+ Add Template",
        ["tmpl.formtitle"]   = "Feeding Template",
        ["tmpl.intro"]       = "Define a feed ration per gender and stage. When you log daily feeding, the lines pre-fill automatically for each animal of that category.",
        ["tmpl.gender"]      = "Gender",
        ["tmpl.stage"]       = "Stage",
        ["tmpl.stage.any"]   = "Any / not applicable",
        ["tmpl.feeds"]       = "Feeds",
        ["tmpl.empty"]       = "No templates yet. Add one to speed up daily feeding.",
        ["feedlog.template_applied"] = "Feeds pre-filled from this animal's feeding template",

        // Wholesale accounts
        ["acct.title"]        = "Wholesale Accounts",
        ["acct.add"]          = "+ Add Account",
        ["acct.addtitle"]     = "New Wholesale Account",
        ["acct.edittitle"]    = "Edit Account",
        ["acct.company"]      = "Company",
        ["acct.owner"]        = "Owner / Contact",
        ["acct.phone"]        = "Phone",
        ["acct.liters_day"]   = "Liters / day",
        ["acct.price"]        = "Price / L",
        ["acct.start"]        = "Start date",
        ["acct.end"]          = "End date",
        ["acct.daily"]        = "Daily (ETB)",
        ["acct.month"]        = "This month",
        ["acct.total"]        = "Billed to date",
        ["acct.daily_est"]    = "Daily income",
        ["acct.active"]       = "Active accounts",
        ["acct.daily_income"] = "Daily income (ETB)",
        ["acct.month_income"] = "This month (ETB)",
        ["acct.activeonly"]   = "Active only",
        ["acct.s.active"]     = "Active",
        ["acct.s.ended"]      = "Ended",
        ["acct.price_btn"]    = "Price",
        ["acct.changeprice"]  = "Change Price",
        ["acct.newprice"]     = "New price / L",
        ["acct.effective"]    = "Effective from",
        ["acct.price_hint"]   = "Days before this date keep the old price; only days from here forward use the new price.",
        ["acct.history"]      = "Price history",
        ["acct.from"]         = "from",
        ["acct.days"]         = "days billed",
        ["acct.delete"]       = "Delete account",
        ["acct.empty"]        = "No accounts yet. Add your first wholesale customer.",
        ["acct.err.company"]  = "Company name is required.",
        ["acct.err.liters"]   = "Liters per day must be greater than 0.",
        ["acct.err.price"]    = "Price must be greater than 0.",

        // Settings
        ["settings.title"]       = "Settings",
        ["settings.tagging"]     = "Cow Tag Numbering",
        ["settings.prefix"]      = "Tag Prefix",
        ["settings.prefix_hint"] = "e.g. ETH, COW, DF — will appear before the number",
        ["settings.next_seq"]    = "Next Sequence Number",
        ["settings.next_tag"]    = "Next tag will be",
        ["settings.saved"]       = "Settings saved",
        ["settings.err.save"]    = "Failed to save settings",
        ["nav.feedlog"]     = "Daily Feeding",

        // Feed inventory
        ["feed.title"]          = "Feed Inventory",
        ["feed.add"]            = "Add Feed",
        ["feed.addtitle"]       = "Add New Feed",
        ["feed.edittitle"]      = "Edit Feed",
        ["feed.name"]           = "Feed Name",
        ["feed.nameph"]         = "e.g. Rhodes Grass Hay",
        ["feed.category"]       = "Category",
        ["feed.unit"]           = "Unit",
        ["feed.stock"]          = "In Stock",
        ["feed.initial_stock"]  = "Initial Stock",
        ["feed.cost_per_unit"]  = "Cost / Unit (ETB)",
        ["feed.restock"]        = "Restock",
        ["feed.restock_qty"]    = "Quantity to Add",
        ["feed.optional"]       = "optional",
        ["feed.empty"]          = "No feed items added yet.",
        ["feed.err.name"]       = "Feed name is required.",
        ["feed.err.save"]       = "Could not save. Please try again.",
        ["feed.err.qty"]        = "Quantity must be greater than 0.",
        ["feed.cat.roughage"]   = "Roughage",
        ["feed.cat.concentrate"]= "Concentrate",
        ["feed.cat.supplement"] = "Supplement",
        ["feed.cat.mineral"]    = "Mineral",

        // Daily feed log
        ["feedlog.title"]       = "Daily Feeding",
        ["feedlog.add"]         = "Log Feeding",
        ["feedlog.addtitle"]    = "Log Feed Consumption",
        ["feedlog.edittitle"]   = "Edit Feed Log",
        ["feedlog.cow"]         = "Cow",
        ["feedlog.cowph"]       = "Select cow",
        ["feedlog.feed"]        = "Feed",
        ["feedlog.feedph"]      = "Select feed",
        ["feedlog.qty_kg"]      = "Quantity (kg)",
        ["feedlog.in_stock"]    = "in stock",
        ["feedlog.cows"]        = "cows",
        ["feedlog.total_today"] = "Total today",
        ["feedlog.empty"]       = "No feeding records for this date.",
        ["feedlog.err.cow"]     = "Please select a cow.",
        ["feedlog.err.feed"]    = "Please select a feed.",
        ["feedlog.err.date"]    = "Invalid date.",
        ["feedlog.addanother"]  = "+ Add another feed",
        ["feedlog.feeds"]       = "Feeds",
        ["feedlog.remove"]      = "Remove",
        ["feedlog.err.items"]   = "Add at least one feed with a quantity.",
        ["feedlog.daily_cost"]  = "Daily Cost (ETB)",
        ["feedlog.cows_fed"]    = "Cows Fed",
        ["lbl.notes"]           = "Notes",
        ["nav.logout"]      = "Logout",
        ["nav.settings"]    = "Settings",

        // Sync
        ["sync.synced"]     = "Synced",
        ["sync.syncing"]    = "Syncing...",
        ["sync.pending"]    = "Pending",
        ["sync.offline"]    = "Offline",
        ["sync.error"]      = "Sync Error",
        ["sync.btn"]        = "Sync",

        // Common
        ["btn.save"]        = "Save",
        ["btn.saving"]      = "Saving...",
        ["btn.cancel"]      = "Cancel",
        ["btn.add"]         = "Add",
        ["btn.edit"]        = "Edit",
        ["btn.resolve"]     = "Resolve",
        ["lbl.date"]        = "Date",
        ["lbl.from"]        = "From",
        ["lbl.to"]          = "To",
        ["lbl.status"]      = "Status",
        ["lbl.total"]       = "Total",
        ["lbl.cost"]        = "Cost (ETB)",
        ["lbl.name"]        = "Name",
        ["lbl.type"]        = "Type",
        ["lbl.page"]        = "Page",
        ["btn.prev"]        = "‹ Prev",
        ["btn.next"]        = "Next ›",
        ["lbl.selectcow"]   = "— Select cow —",
        ["err.savefail"]    = "Failed to save.",
        ["err.selectcow"]   = "Select a cow.",

        // Dashboard
        ["dash.title"]          = "Dashboard",
        ["dash.subtitle"]       = "Farm overview",
        ["dash.totalcows"]      = "Total Cows",
        ["dash.milking"]        = "milking",
        ["dash.dry"]            = "dry",
        ["dash.todaymilk"]      = "Today's Milk",
        ["dash.avgday"]         = "avg/day",
        ["dash.revenue30"]      = "Revenue 30d (ETB)",
        ["dash.profit"]         = "Profit",
        ["dash.healthissues"]   = "Health Issues",
        ["dash.followups"]      = "follow-ups due",
        ["dash.vs_yesterday"]   = "vs yesterday",
        ["dash.yieldcow"]       = "L/cow",
        ["dash.recurring"]      = "Recurring Daily Income (ETB)",
        ["dash.day_committed"]  = "day committed",
        ["dash.netprofit"]      = "Net Profit 30d (ETB)",
        ["dash.margin"]         = "margin",
        ["dash.over30"]         = "last 30 days",
        ["dash.costliter"]      = "Cost / Liter (ETB)",
        ["dash.sellprice"]      = "avg sell price",
        ["dash.supplydemand"]   = "Production vs Wholesale Demand",
        ["dash.coverage"]       = "coverage",
        ["dash.production_avg"] = "Avg daily production",
        ["dash.committed_demand"] = "Committed to wholesale",
        ["dash.surplus"]        = "daily surplus over commitments",
        ["dash.shortfall"]      = "daily shortfall vs commitments",
        ["dash.no_commitments"] = "No active wholesale commitments yet.",
        ["dash.revenue_costs"]  = "Revenue vs Costs (30 days)",
        ["dash.wholesale_income"] = "Wholesale income",
        ["dash.direct_sales"]   = "Direct sales",
        ["dash.total_revenue"]  = "Total revenue",
        ["dash.expenses"]       = "Expenses",
        ["dash.net_profit"]     = "Net profit",
        ["dash.cost_breakdown"] = "Cost Breakdown (30 days)",
        ["dash.feed_cost"]      = "Feed consumed",
        ["dash.no_expenses"]    = "No expenses recorded in the last 30 days.",
        ["dash.trend"]          = "Production — last 14 days",
        ["dash.produced30"]     = "Produced 30d",
        ["dash.wholesale_month"] = "Wholesale this month",
        // Redesigned dashboard
        ["dash.whole_herd"]     = "whole herd",
        ["dash.milking_now"]    = "Milking now",
        ["dash.cov_eyebrow"]    = "Wholesale coverage · today",
        ["dash.no_commit_short"]= "No commitments",
        ["dash.on_target"]      = "On target",
        ["dash.below_commit"]   = "Below commitment",
        ["dash.of"]             = "of",
        ["dash.delivered_toward"]= "delivered toward",
        ["dash.day"]            = "day",
        ["dash.committed_l"]    = "committed",
        ["dash.day30_avg"]      = "30-day avg",
        ["dash.today_cov"]      = "today's coverage",
        ["dash.avg_cov"]        = "30-day avg coverage",
        ["dash.active_account"] = "active account",
        ["dash.active_accounts"]= "active accounts",
        ["dash.short_pre"]      = "Running",
        ["dash.short_mid"]      = "short of the",
        ["dash.short_post"]     = "wholesale commitment — keep the daily fill climbing toward target.",
        ["dash.surplus_pre"]    = "Producing",
        ["dash.surplus_post"]   = "above the",
        ["dash.per_cow"]        = "L per cow",
        ["dash.netprofit_e"]    = "Net profit · 30 days",
        ["dash.costliter_e"]    = "Cost per litre",
        ["dash.produced_e"]     = "Produced · 30 days",
        ["dash.avg_per_day"]    = "L average per day",
        ["dash.billed30"]       = "billed over last 30 days",
        ["dash.l_per_day"]      = "litres / day",
        ["dash.feed_consumed"]  = "Feed consumed",
        ["dash.cost_note"]      = "Add labour, vet, and utilities to sharpen the cost-per-litre figure.",

        // Cows / livestock
        ["cows.title"]          = "Livestock",
        ["cows.add"]            = "+ Add Livestock",
        ["cows.allstatus"]      = "All Status",
        ["cows.type"]           = "Type",
        ["cows.alltypes"]       = "All Types",
        ["type.cow"]            = "Cow (female)",
        ["type.ox"]             = "Ox (male)",
        ["cows.addtitle"]       = "Add Livestock",
        ["cows.edittitle"]      = "Edit Livestock",
        ["cows.dob"]            = "Date of Birth",
        ["cows.tag"]            = "Tag Number *",
        ["cows.tagph"]          = "e.g. C-011",
        ["cows.nameph"]         = "Optional name",
        ["cows.breed"]          = "Breed",
        ["cows.breedph"]        = "e.g. Holstein",
        ["cows.yield"]          = "Expected Yield (L/day)",
        ["cows.col.tag"]        = "Tag",
        ["cows.col.breed"]      = "Breed",
        ["cows.col.yield"]      = "Yield (L)",
        ["cows.col.age"]        = "Age",
        ["cows.empty"]          = "No cows found.",
        ["cows.err.tag"]        = "Tag number is required.",
        ["cows.err.save"]       = "Failed to save cow.",

        // Cow statuses
        ["status.milking"]      = "Milking",
        ["status.dry"]          = "Dry",
        ["status.pregnant"]     = "Pregnant",
        ["status.sick"]         = "Sick",
        ["status.calf"]         = "Calf",

        // Milk
        ["milk.title"]          = "Milk Log",
        ["milk.add"]            = "+ Log Milk",
        ["milk.formtitle"]      = "Log Milk Production",
        ["milk.cowtag"]         = "Cow Tag",
        ["milk.am"]             = "AM (L)",
        ["milk.pm"]             = "PM (L)",
        ["milk.quality"]        = "Quality",
        ["milk.q.normal"]       = "Normal",
        ["milk.q.fresh"]        = "Fresh",
        ["milk.q.mastitis"]     = "Mastitis",
        ["milk.q.colostrum"]    = "Colostrum",
        ["milk.col.cow"]        = "Cow",
        ["milk.col.am"]         = "AM (L)",
        ["milk.col.pm"]         = "PM (L)",
        ["milk.col.total"]      = "Total",
        ["milk.col.quality"]    = "Quality",
        ["milk.empty"]          = "No milk logs found.",
        ["milk.allcows"]        = "Milk per Cow",
        ["milk.nocows"]         = "No milking cows available.",
        ["milk.err.empty"]      = "Enter milk for at least one cow.",

        // Sales
        ["sales.title"]         = "Sales",
        ["sales.add"]           = "+ Record Sale",
        ["sales.formtitle"]     = "Record Sale",
        ["sales.liters"]        = "Liters Sold",
        ["sales.price"]         = "Price/Liter (ETB)",
        ["sales.buyer"]         = "Buyer Name",
        ["sales.payment"]       = "Payment Status",
        ["sales.paid"]          = "Paid",
        ["sales.pending"]       = "Pending",
        ["sales.partial"]       = "Partial",
        ["sales.col.liters"]    = "Liters",
        ["sales.col.pricel"]    = "Price/L",
        ["sales.col.buyer"]     = "Buyer",
        ["sales.empty"]         = "No sales recorded.",
        ["sales.err.fields"]    = "Liters and price are required.",

        // Health
        ["health.title"]        = "Health Records",
        ["health.add"]          = "+ Add Record",
        ["health.formtitle"]    = "Health Record",
        ["health.unresolvedonly"] = "Unresolved only",
        ["health.cow"]          = "Cow",
        ["health.condition"]    = "Condition",
        ["health.treatment"]    = "Treatment",
        ["health.medication"]   = "Medication",
        ["health.t.vaccination"]= "Vaccination",
        ["health.t.treatment"]  = "Treatment",
        ["health.t.checkup"]    = "Checkup",
        ["health.t.deworming"]  = "Deworming",
        ["health.col.type"]     = "Type",
        ["health.col.condition"]= "Condition",
        ["health.col.treatment"]= "Treatment",
        ["health.col.cost"]     = "Cost",
        ["health.resolved"]     = "Resolved",
        ["health.empty"]        = "No health records found.",
        ["health.err.cow"]      = "Select a cow.",

        // Expenses
        ["exp.title"]           = "Expenses",
        ["exp.add"]             = "+ Add Expense",
        ["exp.formtitle"]       = "Record Expense",
        ["exp.category"]        = "Category",
        ["exp.description"]     = "Description",
        ["exp.amount"]          = "Amount (ETB)",
        ["exp.vendor"]          = "Vendor",
        ["exp.c.feed"]          = "Feed",
        ["exp.c.labor"]         = "Labor",
        ["exp.c.vet"]           = "Veterinary",
        ["exp.c.equipment"]     = "Equipment",
        ["exp.c.utilities"]     = "Utilities",
        ["exp.c.other"]         = "Other",
        ["exp.col.category"]    = "Category",
        ["exp.col.desc"]        = "Description",
        ["exp.col.amount"]      = "Amount",
        ["exp.col.vendor"]      = "Vendor",
        ["exp.empty"]           = "No one-time expenses recorded.",
        ["exp.err.fields"]      = "Amount and description are required.",
        ["exp.addtitle"]        = "Add Expense",
        ["exp.edittitle"]       = "Edit Expense",
        ["exp.type"]            = "Type",
        ["exp.t.onetime"]       = "One-time",
        ["exp.t.recurring"]     = "Recurring",
        ["exp.hint.onetime"]    = "A single dated cost — a purchase, a vet visit, a repair.",
        ["exp.hint.recurring"]  = "A cost that repeats (salary, rent, a daily wage). Entered once, accrues over time.",
        ["exp.frequency"]       = "Frequency",
        ["exp.f.daily"]         = "Daily",
        ["exp.f.weekly"]        = "Weekly",
        ["exp.f.monthly"]       = "Monthly",
        ["exp.recurring_note"]  = "This cost accrues evenly each day between the start and end dates.",
        ["exp.recurring_title"] = "Recurring Costs",
        ["exp.onetime_title"]   = "One-time Expenses",
        ["exp.no_recurring"]    = "No recurring costs yet.",
        ["exp.monthly_eq"]      = "Per month",
        ["exp.mo"]              = "mo",
        ["exp.total_cost"]      = "Total cost",
        ["exp.onetime"]         = "One-time",
        ["exp.recurring"]       = "Recurring",
        ["exp.feed_auto"]       = "Feed",
        ["exp.this_month"]      = "this month",
        ["exp.feed_title"]      = "Feed Consumption (auto-tracked)",
        ["exp.feed_desc"]       = "Feed consumed via daily feeding logs",
        ["exp.feed_hint"]       = "Pulled automatically from the Daily Feeding page — no manual entry needed. Logged feeding is counted as cost here and on the dashboard.",

        // Breed categories
        ["breed.cat.local"]     = "Local / Ethiopian",
        ["breed.cat.exotic"]    = "Exotic / International",
        ["breed.cat.cross"]     = "Crossbreed",
        ["breed.cat.other"]     = "Other",

        // Login
        ["login.signin"]        = "Sign In",
        ["login.signinbtn"]     = "Sign In",
        ["login.signingin"]     = "Signing in...",
        ["login.email"]         = "Email",
        ["login.emailph"]       = "you@example.com",
        ["login.password"]      = "Password",
        ["login.passwordph"]    = "••••••••",
        ["login.noaccount"]     = "No account?",
        ["login.registerfarm"]  = "Register your farm",
        ["login.register"]      = "Register Farm",
        ["login.farmname"]      = "Farm Name",
        ["login.farmnameph"]    = "My Dairy Farm",
        ["login.ownername"]     = "Owner Name",
        ["login.ownernameph"]   = "Full Name",
        ["login.passwordph2"]   = "Min. 8 characters",
        ["login.createbtn"]     = "Create Farm",
        ["login.creating"]      = "Creating...",
        ["login.haveaccount"]   = "Have an account?",
        ["login.err.invalid"]   = "Invalid email or password.",
        ["login.err.regfail"]   = "Registration failed. Email may already be in use.",
        ["login.err.fields"]    = "Farm name and owner name are required.",
    };

    // ── Amharic (አማርኛ) ──────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> Am = new()
    {
        // App
        ["app.name"]        = "ዴይሪፍሎው",
        ["app.tagline"]     = "የወተት እርሻ አስተዳደር",

        // Nav
        ["nav.dashboard"]   = "ዳሽቦርድ",
        ["nav.cows"]        = "ከብቶች",
        ["nav.milk"]        = "የወተት ምዝገባ",
        ["nav.sales"]       = "ሽያጮች",
        ["nav.health"]      = "ጤና",
        ["nav.expenses"]    = "ወጪዎች",
        ["nav.feed"]        = "የምግብ ክምችት",
        ["nav.feedtemplates"] = "የአመጋገብ አብነቶች",
        ["nav.accounts"]    = "ሒሳቦች",

        // Feeding templates
        ["tmpl.title"]       = "የአመጋገብ አብነቶች",
        ["tmpl.add"]         = "+ አብነት ጨምር",
        ["tmpl.formtitle"]   = "የአመጋገብ አብነት",
        ["tmpl.intro"]       = "በጾታና በደረጃ የምግብ መጠን ይግለጹ። ዕለታዊ አመጋገብ ሲመዘግቡ፣ ለእያንዳንዱ የዚያ ምድብ እንስሳ መስመሮቹ በራስ-ሰር ይሞላሉ።",
        ["tmpl.gender"]      = "ጾታ",
        ["tmpl.stage"]       = "ደረጃ",
        ["tmpl.stage.any"]   = "ማንኛውም / አይመለከትም",
        ["tmpl.feeds"]       = "ምግቦች",
        ["tmpl.empty"]       = "እስካሁን አብነት የለም። ዕለታዊ አመጋገብን ለማፋጠን አንድ ይጨምሩ።",
        ["feedlog.template_applied"] = "ምግቦች ከዚህ እንስሳ የአመጋገብ አብነት ተሞልተዋል",

        // Wholesale accounts
        ["acct.title"]        = "የጅምላ ሒሳቦች",
        ["acct.add"]          = "+ ሒሳብ ጨምር",
        ["acct.addtitle"]     = "አዲስ የጅምላ ሒሳብ",
        ["acct.edittitle"]    = "ሒሳብ አርትዕ",
        ["acct.company"]      = "ድርጅት",
        ["acct.owner"]        = "ባለቤት / አግኚ",
        ["acct.phone"]        = "ስልክ",
        ["acct.liters_day"]   = "ሊትር / ቀን",
        ["acct.price"]        = "ዋጋ / ሊ",
        ["acct.start"]        = "የመጀመሪያ ቀን",
        ["acct.end"]          = "የመጨረሻ ቀን",
        ["acct.daily"]        = "ዕለታዊ (ብር)",
        ["acct.month"]        = "በዚህ ወር",
        ["acct.total"]        = "እስካሁን የተከፈለ",
        ["acct.daily_est"]    = "ዕለታዊ ገቢ",
        ["acct.active"]       = "ንቁ ሒሳቦች",
        ["acct.daily_income"] = "ዕለታዊ ገቢ (ብር)",
        ["acct.month_income"] = "በዚህ ወር (ብር)",
        ["acct.activeonly"]   = "ንቁ ብቻ",
        ["acct.s.active"]     = "ንቁ",
        ["acct.s.ended"]      = "ተጠናቋል",
        ["acct.price_btn"]    = "ዋጋ",
        ["acct.changeprice"]  = "ዋጋ ቀይር",
        ["acct.newprice"]     = "አዲስ ዋጋ / ሊ",
        ["acct.effective"]    = "ከቀን ጀምሮ",
        ["acct.price_hint"]   = "ከዚህ ቀን በፊት ያሉ ቀናት የቀድሞውን ዋጋ ይይዛሉ፤ ከዚህ ቀን ጀምሮ ብቻ አዲሱ ዋጋ ይሰራል።",
        ["acct.history"]      = "የዋጋ ታሪክ",
        ["acct.from"]         = "ከ",
        ["acct.days"]         = "ቀናት ተከፍለዋል",
        ["acct.delete"]       = "ሒሳብ ሰርዝ",
        ["acct.empty"]        = "እስካሁን ሒሳብ የለም። የመጀመሪያ የጅምላ ደንበኛዎን ይጨምሩ።",
        ["acct.err.company"]  = "የድርጅት ስም ያስፈልጋል።",
        ["acct.err.liters"]   = "በቀን የሚሰጠው ሊትር ከ0 በላይ መሆን አለበት።",
        ["acct.err.price"]    = "ዋጋ ከ0 በላይ መሆን አለበት።",

        // Settings
        ["settings.title"]       = "ቅንብሮች",
        ["settings.tagging"]     = "የከብት መታወቂያ ቁጥር",
        ["settings.prefix"]      = "የቁጥር ቅድመ-ቅጥያ",
        ["settings.prefix_hint"] = "ለምሳሌ ETH፣ COW፣ DF",
        ["settings.next_seq"]    = "ቀጣይ ቁጥር",
        ["settings.next_tag"]    = "ቀጣዩ መለያ",
        ["settings.saved"]       = "ቅንብሮች ተቀምጠዋል",
        ["settings.err.save"]    = "ቅንብሮችን ማስቀመጥ አልተቻለም",
        ["nav.feedlog"]     = "ዕለታዊ አመጋገብ",

        // Feed
        ["feed.title"]          = "የምግብ ክምችት",
        ["feed.add"]            = "ምግብ ጨምር",
        ["feed.addtitle"]       = "አዲስ ምግብ ጨምር",
        ["feed.edittitle"]      = "ምግብ አርትዕ",
        ["feed.name"]           = "የምግብ ስም",
        ["feed.nameph"]         = "ለምሳሌ፦ ሮድስ ሳር",
        ["feed.category"]       = "ምድብ",
        ["feed.unit"]           = "መለኪያ",
        ["feed.stock"]          = "ያለው ክምችት",
        ["feed.initial_stock"]  = "መጀመሪያ ክምችት",
        ["feed.cost_per_unit"]  = "ዋጋ / አሃድ (ብር)",
        ["feed.restock"]        = "ክምችት ጨምር",
        ["feed.restock_qty"]    = "የሚጨመር መጠን",
        ["feed.optional"]       = "አስፈላጊ ካልሆነ",
        ["feed.empty"]          = "ምንም ምግብ አልተጨመረም።",
        ["feed.err.name"]       = "የምግብ ስም ያስፈልጋል።",
        ["feed.err.save"]       = "ማስቀመጥ አልተቻለም። እንደገና ይሞክሩ።",
        ["feed.err.qty"]        = "መጠኑ ከ0 በላይ መሆን አለበት።",
        ["feed.cat.roughage"]   = "ሳር/ቆሻሻ",
        ["feed.cat.concentrate"]= "ማጎሪያ",
        ["feed.cat.supplement"] = "ተጨማሪ ምግብ",
        ["feed.cat.mineral"]    = "ማዕድን",

        // Feed log
        ["feedlog.title"]       = "ዕለታዊ አመጋገብ",
        ["feedlog.add"]         = "አመጋገብ ሪፖርት",
        ["feedlog.addtitle"]    = "አመጋገብ ሪፖርት ጨምር",
        ["feedlog.edittitle"]   = "አመጋገብ ሪፖርት አርትዕ",
        ["feedlog.cow"]         = "ላም",
        ["feedlog.cowph"]       = "ላም ይምረጡ",
        ["feedlog.feed"]        = "ምግብ",
        ["feedlog.feedph"]      = "ምግብ ይምረጡ",
        ["feedlog.qty_kg"]      = "መጠን (ኪ.ግ)",
        ["feedlog.in_stock"]    = "ክምችት",
        ["feedlog.cows"]        = "ላሞች",
        ["feedlog.total_today"] = "ዛሬ ጠቅላላ",
        ["feedlog.empty"]       = "ለዚህ ቀን ምንም ሪፖርት የለም።",
        ["feedlog.err.cow"]     = "ላም ይምረጡ።",
        ["feedlog.err.feed"]    = "ምግብ ይምረጡ።",
        ["feedlog.err.date"]    = "ቀኑ ትክክል አይደለም።",
        ["feedlog.addanother"]  = "+ ሌላ ምግብ ጨምር",
        ["feedlog.feeds"]       = "ምግቦች",
        ["feedlog.remove"]      = "አስወግድ",
        ["feedlog.err.items"]   = "ቢያንስ አንድ ምግብ ከመጠን ጋር ጨምሩ።",
        ["feedlog.daily_cost"]  = "የቀኑ ወጪ (ብር)",
        ["feedlog.cows_fed"]    = "የተመገቡ ላሞች",
        ["lbl.notes"]           = "ማስታወሻ",
        ["nav.logout"]      = "ውጣ",
        ["nav.settings"]    = "ቅንብሮች",

        // Sync
        ["sync.synced"]     = "ተሳስቷል",
        ["sync.syncing"]    = "በማስተሳሰር...",
        ["sync.pending"]    = "በመጠባበቅ",
        ["sync.offline"]    = "ከመስመር ውጪ",
        ["sync.error"]      = "የማስተሳሰር ስህተት",
        ["sync.btn"]        = "አስተሳስር",

        // Common
        ["btn.save"]        = "አስቀምጥ",
        ["btn.saving"]      = "በማስቀመጥ...",
        ["btn.cancel"]      = "ሰርዝ",
        ["btn.add"]         = "ጨምር",
        ["btn.edit"]        = "አርትዕ",
        ["btn.resolve"]     = "ፍታ",
        ["lbl.date"]        = "ቀን",
        ["lbl.from"]        = "ከ",
        ["lbl.to"]          = "እስከ",
        ["lbl.status"]      = "ሁኔታ",
        ["lbl.total"]       = "ጠቅላላ",
        ["lbl.cost"]        = "ወጪ (ብር)",
        ["lbl.name"]        = "ስም",
        ["lbl.type"]        = "አይነት",
        ["lbl.page"]        = "ገጽ",
        ["btn.prev"]        = "‹ ቀደምት",
        ["btn.next"]        = "ቀጣይ ›",
        ["lbl.selectcow"]   = "— ላም ምረጥ —",
        ["err.savefail"]    = "ማስቀመጥ አልተሳካም።",
        ["err.selectcow"]   = "ላም ይምረጡ።",

        // Dashboard
        ["dash.title"]          = "ዳሽቦርድ",
        ["dash.subtitle"]       = "የእርሻ አጠቃላይ እይታ",
        ["dash.totalcows"]      = "ጠቅላላ ላሞች",
        ["dash.milking"]        = "ወተት ሰጪ",
        ["dash.dry"]            = "ደረቅ",
        ["dash.todaymilk"]      = "የዛሬ ወተት",
        ["dash.avgday"]         = "አማካኝ/ቀን",
        ["dash.revenue30"]      = "ገቢ 30 ቀን (ብር)",
        ["dash.profit"]         = "ትርፍ",
        ["dash.healthissues"]   = "የጤና ጉዳዮች",
        ["dash.followups"]      = "ክትትል ያስፈልጋቸው",
        ["dash.vs_yesterday"]   = "ከትናንት ጋር",
        ["dash.yieldcow"]       = "ሊ/ላም",
        ["dash.recurring"]      = "ቋሚ ዕለታዊ ገቢ (ብር)",
        ["dash.day_committed"]  = "ቀን ቃል የተገባ",
        ["dash.netprofit"]      = "የተጣራ ትርፍ 30 ቀን (ብር)",
        ["dash.margin"]         = "ህዳግ",
        ["dash.over30"]         = "ባለፉት 30 ቀናት",
        ["dash.costliter"]      = "ወጪ / ሊትር (ብር)",
        ["dash.sellprice"]      = "አማካኝ የመሸጫ ዋጋ",
        ["dash.supplydemand"]   = "ምርት ከጅምላ ፍላጎት ጋር",
        ["dash.coverage"]       = "ሽፋን",
        ["dash.production_avg"] = "አማካኝ ዕለታዊ ምርት",
        ["dash.committed_demand"] = "ለጅምላ ቃል የተገባ",
        ["dash.surplus"]        = "ዕለታዊ ትርፍ ከቃል በላይ",
        ["dash.shortfall"]      = "ዕለታዊ እጥረት ከቃል በታች",
        ["dash.no_commitments"] = "እስካሁን ንቁ የጅምላ ቃል የለም።",
        ["dash.revenue_costs"]  = "ገቢ ከወጪ ጋር (30 ቀን)",
        ["dash.wholesale_income"] = "የጅምላ ገቢ",
        ["dash.direct_sales"]   = "ቀጥታ ሽያጭ",
        ["dash.total_revenue"]  = "ጠቅላላ ገቢ",
        ["dash.expenses"]       = "ወጪዎች",
        ["dash.net_profit"]     = "የተጣራ ትርፍ",
        ["dash.cost_breakdown"] = "የወጪ ዝርዝር (30 ቀን)",
        ["dash.feed_cost"]      = "የተበላ ምግብ",
        ["dash.no_expenses"]    = "ባለፉት 30 ቀናት ምንም ወጪ አልተመዘገበም።",
        ["dash.trend"]          = "ምርት — ባለፉት 14 ቀናት",
        ["dash.produced30"]     = "ምርት 30 ቀን",
        ["dash.wholesale_month"] = "የጅምላ በዚህ ወር",
        // Redesigned dashboard
        ["dash.whole_herd"]     = "ሙሉ መንጋ",
        ["dash.milking_now"]    = "አሁን የሚታለቡ",
        ["dash.cov_eyebrow"]    = "የጅምላ ሽፋን · ዛሬ",
        ["dash.no_commit_short"]= "ምንም ቃል የለም",
        ["dash.on_target"]      = "ግቡን አሳክቷል",
        ["dash.below_commit"]   = "ከቃል በታች",
        ["dash.of"]             = "ከ",
        ["dash.delivered_toward"]= "ከደረሰ",
        ["dash.day"]            = "ቀን",
        ["dash.committed_l"]    = "ቃል የተገባ",
        ["dash.day30_avg"]      = "የ30 ቀን አማካኝ",
        ["dash.today_cov"]      = "የዛሬ ሽፋን",
        ["dash.avg_cov"]        = "የ30 ቀን አማካኝ ሽፋን",
        ["dash.active_account"] = "ንቁ ሒሳብ",
        ["dash.active_accounts"]= "ንቁ ሒሳቦች",
        ["dash.short_pre"]      = "በ",
        ["dash.short_mid"]      = "ከ",
        ["dash.short_post"]     = "ሊትር የጅምላ ቃል በታች ነው — ዕለታዊ ምርቱን ወደ ግቡ ከፍ ያድርጉ።",
        ["dash.surplus_pre"]    = "በ",
        ["dash.surplus_post"]   = "ከ",
        ["dash.per_cow"]        = "ሊ በላም",
        ["dash.netprofit_e"]    = "የተጣራ ትርፍ · 30 ቀን",
        ["dash.costliter_e"]    = "ወጪ በሊትር",
        ["dash.produced_e"]     = "ምርት · 30 ቀን",
        ["dash.avg_per_day"]    = "ሊ አማካኝ በቀን",
        ["dash.billed30"]       = "ባለፉት 30 ቀናት የተከፈለ",
        ["dash.l_per_day"]      = "ሊትር / ቀን",
        ["dash.feed_consumed"]  = "የተበላ ምግብ",
        ["dash.cost_note"]      = "የወጪ-በሊትር አሃዙን ለማሻሻል ጉልበት፣ ሕክምና እና አገልግሎቶችን ይጨምሩ።",

        // Cows / livestock
        ["cows.title"]          = "ከብቶች",
        ["cows.add"]            = "+ ከብት ጨምር",
        ["cows.allstatus"]      = "ሁሉም ሁኔታ",
        ["cows.type"]           = "ዓይነት",
        ["cows.alltypes"]       = "ሁሉም ዓይነት",
        ["type.cow"]            = "ላም (ሴት)",
        ["type.ox"]             = "በሬ (ወንድ)",
        ["cows.addtitle"]       = "ከብት ጨምር",
        ["cows.edittitle"]      = "ከብት አርትዕ",
        ["cows.dob"]            = "የልደት ቀን",
        ["cows.tag"]            = "መለያ ቁጥር *",
        ["cows.tagph"]          = "ለምሳሌ C-011",
        ["cows.nameph"]         = "አማራጭ ስም",
        ["cows.breed"]          = "ዝርያ",
        ["cows.breedph"]        = "ለምሳሌ Holstein",
        ["cows.yield"]          = "የሚጠበቅ ምርት (ሊ/ቀን)",
        ["cows.col.tag"]        = "መለያ",
        ["cows.col.breed"]      = "ዝርያ",
        ["cows.col.yield"]      = "ምርት (ሊ)",
        ["cows.col.age"]        = "እድሜ",
        ["cows.empty"]          = "ምንም ላም አልተገኘም።",
        ["cows.err.tag"]        = "የመለያ ቁጥር ያስፈልጋል።",
        ["cows.err.save"]       = "ላሙን ማስቀመጥ አልተሳካም።",

        // Cow statuses
        ["status.milking"]      = "ወተት ሰጪ",
        ["status.dry"]          = "ደረቅ",
        ["status.pregnant"]     = "ነፍሰ ጡር",
        ["status.sick"]         = "ታሞ",
        ["status.calf"]         = "ጥጃ",

        // Milk
        ["milk.title"]          = "የወተት ምዝገባ",
        ["milk.add"]            = "+ ወተት መዝግብ",
        ["milk.formtitle"]      = "የወተት ምርት ምዝገባ",
        ["milk.cowtag"]         = "የላም መለያ",
        ["milk.am"]             = "ጥዋት (ሊ)",
        ["milk.pm"]             = "ከሰዓት (ሊ)",
        ["milk.quality"]        = "ጥራት",
        ["milk.q.normal"]       = "መደበኛ",
        ["milk.q.fresh"]        = "ትኩስ",
        ["milk.q.mastitis"]     = "ማስቲቲስ",
        ["milk.q.colostrum"]    = "ቅድም ወተት",
        ["milk.col.cow"]        = "ላም",
        ["milk.col.am"]         = "ጥዋት (ሊ)",
        ["milk.col.pm"]         = "ከሰዓት (ሊ)",
        ["milk.col.total"]      = "ጠቅላላ",
        ["milk.col.quality"]    = "ጥራት",
        ["milk.empty"]          = "ምንም የወተት ምዝገባ አልተገኘም።",
        ["milk.allcows"]        = "ወተት በላም",
        ["milk.nocows"]         = "ወተት ሰጪ ላሞች የሉም።",
        ["milk.err.empty"]      = "ቢያንስ ለአንድ ላም ወተት ያስገቡ።",

        // Sales
        ["sales.title"]         = "ሽያጮች",
        ["sales.add"]           = "+ ሽያጭ መዝግብ",
        ["sales.formtitle"]     = "ሽያጭ ምዝገባ",
        ["sales.liters"]        = "የተሸጠ ሊትር",
        ["sales.price"]         = "ዋጋ/ሊትር (ብር)",
        ["sales.buyer"]         = "ገዢ ስም",
        ["sales.payment"]       = "የክፍያ ሁኔታ",
        ["sales.paid"]          = "ተከፍሏል",
        ["sales.pending"]       = "በመጠባበቅ",
        ["sales.partial"]       = "ከፊል",
        ["sales.col.liters"]    = "ሊትር",
        ["sales.col.pricel"]    = "ዋጋ/ሊ",
        ["sales.col.buyer"]     = "ገዢ",
        ["sales.empty"]         = "ምንም ሽያጭ አልተመዘገበም።",
        ["sales.err.fields"]    = "ሊትር እና ዋጋ ያስፈልጋሉ።",

        // Health
        ["health.title"]        = "የጤና መዝገቦች",
        ["health.add"]          = "+ መዝገብ ጨምር",
        ["health.formtitle"]    = "የጤና መዝገብ",
        ["health.unresolvedonly"] = "ያልተፈቱ ብቻ",
        ["health.cow"]          = "ላም",
        ["health.condition"]    = "ሁኔታ",
        ["health.treatment"]    = "ሕክምና",
        ["health.medication"]   = "መድሃኒት",
        ["health.t.vaccination"]= "ክትባት",
        ["health.t.treatment"]  = "ሕክምና",
        ["health.t.checkup"]    = "ምርመራ",
        ["health.t.deworming"]  = "ትል ማስወጣት",
        ["health.col.type"]     = "አይነት",
        ["health.col.condition"]= "ሁኔታ",
        ["health.col.treatment"]= "ሕክምና",
        ["health.col.cost"]     = "ወጪ",
        ["health.resolved"]     = "ተፍቷል",
        ["health.empty"]        = "ምንም የጤና መዝገብ አልተገኘም።",
        ["health.err.cow"]      = "ላም ይምረጡ።",

        // Expenses
        ["exp.title"]           = "ወጪዎች",
        ["exp.add"]             = "+ ወጪ ጨምር",
        ["exp.formtitle"]       = "ወጪ ምዝገባ",
        ["exp.category"]        = "ምድብ",
        ["exp.description"]     = "መግለጫ",
        ["exp.amount"]          = "መጠን (ብር)",
        ["exp.vendor"]          = "አቅራቢ",
        ["exp.c.feed"]          = "ምግብ",
        ["exp.c.labor"]         = "ጉልበት",
        ["exp.c.vet"]           = "ሕክምናዊ",
        ["exp.c.equipment"]     = "መሳሪያ",
        ["exp.c.utilities"]     = "አገልግሎቶች",
        ["exp.c.other"]         = "ሌሎች",
        ["exp.col.category"]    = "ምድብ",
        ["exp.col.desc"]        = "መግለጫ",
        ["exp.col.amount"]      = "መጠን",
        ["exp.col.vendor"]      = "አቅራቢ",
        ["exp.empty"]           = "ምንም የአንድ ጊዜ ወጪ አልተመዘገበም።",
        ["exp.err.fields"]      = "መጠን እና መግለጫ ያስፈልጋሉ።",
        ["exp.addtitle"]        = "ወጪ ጨምር",
        ["exp.edittitle"]       = "ወጪ አርትዕ",
        ["exp.type"]            = "ዓይነት",
        ["exp.t.onetime"]       = "የአንድ ጊዜ",
        ["exp.t.recurring"]     = "ተደጋጋሚ",
        ["exp.hint.onetime"]    = "ነጠላ የቀን ወጪ — ግዢ፣ የእንስሳት ሐኪም ጉብኝት፣ ጥገና።",
        ["exp.hint.recurring"]  = "የሚደጋገም ወጪ (ደመወዝ፣ ኪራይ፣ ዕለታዊ ክፍያ)። አንዴ ይገባል፣ በጊዜ ይከማቻል።",
        ["exp.frequency"]       = "ድግግሞሽ",
        ["exp.f.daily"]         = "ዕለታዊ",
        ["exp.f.weekly"]        = "ሳምንታዊ",
        ["exp.f.monthly"]       = "ወርሃዊ",
        ["exp.recurring_note"]  = "ይህ ወጪ በመጀመሪያና በመጨረሻ ቀናት መካከል በየቀኑ እኩል ይከማቻል።",
        ["exp.recurring_title"] = "ተደጋጋሚ ወጪዎች",
        ["exp.onetime_title"]   = "የአንድ ጊዜ ወጪዎች",
        ["exp.no_recurring"]    = "እስካሁን ተደጋጋሚ ወጪ የለም።",
        ["exp.monthly_eq"]      = "በወር",
        ["exp.mo"]              = "ወር",
        ["exp.total_cost"]      = "ጠቅላላ ወጪ",
        ["exp.onetime"]         = "የአንድ ጊዜ",
        ["exp.recurring"]       = "ተደጋጋሚ",
        ["exp.feed_auto"]       = "ምግብ",
        ["exp.this_month"]      = "በዚህ ወር",
        ["exp.feed_title"]      = "የምግብ ፍጆታ (በራስ-ሰር)",
        ["exp.feed_desc"]       = "በዕለታዊ አመጋገብ ምዝገባ የተበላ ምግብ",
        ["exp.feed_hint"]       = "ከዕለታዊ አመጋገብ ገጽ በራስ-ሰር ይወሰዳል — በእጅ ማስገባት አያስፈልግም። የተመዘገበ አመጋገብ እዚህና በዳሽቦርዱ እንደ ወጪ ይቆጠራል።",

        // Breed categories
        ["breed.cat.local"]     = "ሀገር በቀል / ኢትዮጵያዊ",
        ["breed.cat.exotic"]    = "የውጭ / ዓለም አቀፍ",
        ["breed.cat.cross"]     = "ድቅልቅ",
        ["breed.cat.other"]     = "ሌላ",

        // Login
        ["login.signin"]        = "ግባ",
        ["login.signinbtn"]     = "ግባ",
        ["login.signingin"]     = "በመግባት ላይ...",
        ["login.email"]         = "ኢሜይል",
        ["login.emailph"]       = "you@example.com",
        ["login.password"]      = "የይለፍ ቃል",
        ["login.passwordph"]    = "••••••••",
        ["login.noaccount"]     = "መለያ የለህም?",
        ["login.registerfarm"]  = "እርሻህን ምዝገብ",
        ["login.register"]      = "እርሻ ምዝገባ",
        ["login.farmname"]      = "የእርሻ ስም",
        ["login.farmnameph"]    = "የኔ ወተት እርሻ",
        ["login.ownername"]     = "የባለቤት ስም",
        ["login.ownernameph"]   = "ሙሉ ስም",
        ["login.passwordph2"]   = "ቢያንስ 8 ቁምፊዎች",
        ["login.createbtn"]     = "እርሻ ፍጠር",
        ["login.creating"]      = "በመፍጠር ላይ...",
        ["login.haveaccount"]   = "መለያ አለህ?",
        ["login.err.invalid"]   = "ትክክለኛ ያልሆነ ኢሜይል ወይም የይለፍ ቃል።",
        ["login.err.regfail"]   = "ምዝገባ አልተሳካም። ኢሜይሉ አስቀድሞ ጥቅም ላይ ሊሆን ይችላል።",
        ["login.err.fields"]    = "የእርሻ ስም እና የባለቤት ስም ያስፈልጋሉ።",
    };
}
